//! Business rules, workflow locks, multi-call orchestration; calls db::*; no
//! SurrealQL text.

pub mod appointment;
pub mod appointment_slot;
pub mod badge;
pub mod builder;
pub mod chatbot_message;
pub mod chatbot_thread;
pub mod class_blueprint;
pub mod course;
pub mod course_session;
pub mod enrollment;
pub mod event;
pub mod exam;
pub mod exam_attempt;
pub mod exam_question;
pub mod meal_booking;
pub mod message;
pub mod note;
pub mod parent_link;
pub mod payment_ledger;
pub mod pomodoro;
pub mod profile;
pub mod rag_output;
pub mod registration;
pub mod session;
pub mod settings;
pub mod subject;
pub mod term;
pub mod user;
pub mod work_entry;
